<?php
/**
 * Data source for Nomade Media — events and spots.
 * Replace by a DB or admin back-office later.
 */

$events = [
    [
        'id' => 'escapades-musicales-2026',
        'title' => 'Les Escapades Musicales',
        'date' => '2026-06-18',
        'date_end' => '2026-07-18',
        'date_label' => '18 juin → 18 juillet',
        'location' => 'Tout le bassin',
        'category' => 'Festival',
        'tag' => 'Musique classique',
        'price' => 'Gratuit - 18 ans',
        'image' => 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&auto=format&fit=crop',
        'description' => 'Festival international de musique classique dans les plus beaux lieux du bassin. Un mois de concerts d\'exception au cœur du patrimoine arcachonnais.',
        'highlight' => true,
    ],
    [
        'id' => 'suzane-velodrome',
        'title' => 'Suzane en concert',
        'date' => '2026-08-03',
        'date_label' => '3 août 2026',
        'location' => 'Vélodrome d\'Arcachon',
        'category' => 'Concert',
        'tag' => 'Électro-pop',
        'price' => '35€',
        'image' => 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop',
        'description' => 'La chanteuse Suzane embrase le Vélodrome pour une soirée Arcachon en Scène sous les étoiles.',
        'highlight' => true,
    ],
    [
        'id' => 'mika-velodrome',
        'title' => 'Mika — Arcachon en Scène',
        'date' => '2026-08-04',
        'date_label' => '4 août 2026',
        'location' => 'Vélodrome d\'Arcachon',
        'category' => 'Concert',
        'tag' => 'Pop internationale',
        'price' => '49€',
        'image' => 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200&auto=format&fit=crop',
        'description' => 'Mika revient en France pour une soirée explosive face au bassin. Un des temps forts de l\'été 2026.',
        'highlight' => true,
    ],
    [
        'id' => 'fetes-de-la-mer',
        'title' => 'Fêtes de la Mer',
        'date' => '2026-08-14',
        'date_end' => '2026-08-15',
        'date_label' => '14 & 15 août',
        'location' => 'Front de mer d\'Arcachon',
        'category' => 'Tradition',
        'tag' => 'Gratuit',
        'price' => 'Gratuit',
        'image' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop',
        'description' => 'Pique-nique géant, défilé nautique, traditions et animations. Le plus gros rassemblement populaire de l\'été.',
        'highlight' => false,
    ],
    [
        'id' => 'cadences-2026',
        'title' => 'Festival Cadences',
        'date' => '2026-09-29',
        'date_end' => '2026-10-04',
        'date_label' => '29 sept → 4 oct',
        'location' => 'Théâtre Olympia & Théâtre de la Mer',
        'category' => 'Festival',
        'tag' => 'Danse',
        'price' => 'Dès 12€',
        'image' => 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&auto=format&fit=crop',
        'description' => 'La danse sous toutes ses formes envahit Arcachon : spectacles en salle, sur la plage et dans la rue.',
        'highlight' => false,
    ],
    [
        'id' => 'frappadingue-arcachon',
        'title' => 'La Frappadingue revient',
        'date' => '2026-05-03',
        'date_label' => '3 mai 2026',
        'location' => 'Plage d\'Arcachon',
        'category' => 'Sport',
        'tag' => 'Course à obstacles',
        'price' => 'Dès 29€',
        'image' => 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=1200&auto=format&fit=crop',
        'description' => 'La course à obstacles XXL qui transforme la plage d\'Arcachon en terrain de jeu géant. Ambiance garantie.',
        'highlight' => true,
    ],
    [
        'id' => 'marche-nocturne-teste',
        'title' => 'Marché nocturne de La Teste',
        'date' => '2026-07-10',
        'date_end' => '2026-08-28',
        'date_label' => 'Tous les vendredis soirs',
        'location' => 'Port de La Teste-de-Buch',
        'category' => 'Marché',
        'tag' => 'Food & artisanat',
        'price' => 'Gratuit',
        'image' => 'https://images.unsplash.com/photo-1555529902-5261145633bf?w=1200&auto=format&fit=crop',
        'description' => 'Producteurs locaux, street food, artisans et concerts live. Le rendez-vous du vendredi soir de juillet à août.',
        'highlight' => false,
    ],
    [
        'id' => 'regate-pinasses',
        'title' => 'Régate des Pinasses',
        'date' => '2026-07-19',
        'date_label' => '19 juillet 2026',
        'location' => 'Bassin d\'Arcachon',
        'category' => 'Tradition',
        'tag' => 'Nautisme',
        'price' => 'Gratuit',
        'image' => 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop',
        'description' => 'Les bateaux traditionnels du bassin s\'affrontent sous voile. Un spectacle inscrit au patrimoine du bassin.',
        'highlight' => false,
    ],
];

$spots = [
    // RESTOS
    [
        'id' => 'chez-hortense',
        'name' => 'Chez Hortense',
        'category' => 'resto',
        'category_label' => 'Resto',
        'location' => 'Cap Ferret',
        'tag' => 'Institution',
        'price_level' => '€€€',
        'image' => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&auto=format&fit=crop',
        'description' => 'Institution du Cap Ferret depuis 4 générations. Terrasse face à la Dune du Pilat, moules-frites mythiques.',
        'instagram' => 'https://www.instagram.com/chezhortense/',
    ],
    [
        'id' => 'cabane-mimbeau',
        'name' => 'La Cabane du Mimbeau',
        'category' => 'resto',
        'category_label' => 'Resto',
        'location' => 'Cap Ferret',
        'tag' => 'Huîtres',
        'price_level' => '€€',
        'image' => 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=1200&auto=format&fit=crop',
        'description' => 'Terrasse panoramique sur la conche du Mimbeau, les meilleures huîtres du bassin loin de l\'agitation du village.',
        'instagram' => '#',
    ],
    [
        'id' => 'le-sail-fish',
        'name' => 'Le Sail Fish',
        'category' => 'resto',
        'category_label' => 'Resto',
        'location' => 'Lège-Cap-Ferret',
        'tag' => 'DJ & dîner',
        'price_level' => '€€€',
        'image' => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop',
        'description' => 'Poissons, viandes grillées, cocktails, puis DJ et piste de danse. La soirée commence à table.',
        'instagram' => '#',
    ],
    [
        'id' => 'bon-endroit-teste',
        'name' => 'Bon Endroit',
        'category' => 'resto',
        'category_label' => 'Resto',
        'location' => 'La Teste-de-Buch',
        'tag' => 'Brunch',
        'price_level' => '€€',
        'image' => 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=1200&auto=format&fit=crop',
        'description' => 'Concept store / café / cantine : brunch le dimanche, ambiance déco bohème et produits locaux.',
        'instagram' => '#',
    ],
    // BARS
    [
        'id' => 'la-madrague',
        'name' => 'La Madrague',
        'category' => 'bar',
        'category_label' => 'Bar',
        'location' => 'Cap Ferret',
        'tag' => 'Cocktails XXL',
        'price_level' => '€€',
        'image' => 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=1200&auto=format&fit=crop',
        'description' => 'Les cocktails XXL à partager entre potes. Spot incontournable des étés au Cap.',
        'instagram' => 'https://www.instagram.com/la_madrague_ferret/',
    ],
    [
        'id' => 'paris-pyla',
        'name' => 'Paris Pyla',
        'category' => 'bar',
        'category_label' => 'Bar',
        'location' => 'Le Moulleau',
        'tag' => 'Légendaire',
        'price_level' => '€€€',
        'image' => 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=1200&auto=format&fit=crop',
        'description' => 'Le bar mythique du Moulleau de retour. Au cœur de la zone piétonne, pour voir et être vu.',
        'instagram' => '#',
    ],
    [
        'id' => 'la-guitoune',
        'name' => 'La Guitoune',
        'category' => 'bar',
        'category_label' => 'Bar',
        'location' => 'Pyla-sur-Mer',
        'tag' => 'Summer vibes',
        'price_level' => '€€',
        'image' => 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=1200&auto=format&fit=crop',
        'description' => 'Ambiance conviviale, good vibes et soirées d\'été qui durent tard. Le spot à apéro du Pyla.',
        'instagram' => '#',
    ],
    [
        'id' => 'chez-fernande',
        'name' => 'Chez Fernande',
        'category' => 'bar',
        'category_label' => 'Bar',
        'location' => 'Arcachon',
        'tag' => 'Cocktails',
        'price_level' => '€€',
        'image' => 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=1200&auto=format&fit=crop',
        'description' => 'Les meilleurs cocktails du Sud-Ouest : créations maison, ingrédients frais, ambiance coucher de soleil.',
        'instagram' => '#',
    ],
    // PLAGES
    [
        'id' => 'dune-pilat',
        'name' => 'Dune du Pilat',
        'category' => 'plage',
        'category_label' => 'Plage',
        'location' => 'La Teste-de-Buch',
        'tag' => 'Iconique',
        'price_level' => '€',
        'image' => 'https://images.unsplash.com/photo-1590167482431-0bf6fa7a8c02?w=1200&auto=format&fit=crop',
        'description' => 'La plus haute dune d\'Europe. Coucher de soleil obligatoire au moins une fois dans ta vie.',
        'instagram' => '#',
    ],
    [
        'id' => 'plage-pereire',
        'name' => 'Plage Pereire',
        'category' => 'plage',
        'category_label' => 'Plage',
        'location' => 'Arcachon',
        'tag' => 'Pins & bassin',
        'price_level' => 'Gratuit',
        'image' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop',
        'description' => 'Sable fin, pinède en arrière-plan et vue imprenable sur le bassin. La plage parfaite pour la journée.',
        'instagram' => '#',
    ],
    [
        'id' => 'plage-lagune',
        'name' => 'Plage de la Lagune',
        'category' => 'plage',
        'category_label' => 'Plage',
        'location' => 'La Teste-de-Buch',
        'tag' => 'Sauvage',
        'price_level' => 'Gratuit',
        'image' => 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&auto=format&fit=crop',
        'description' => 'Plage océan au sud du Pilat, vagues et grands espaces. Le spot des surfeurs et des longues balades.',
        'instagram' => '#',
    ],
    [
        'id' => 'grand-crohot',
        'name' => 'Le Grand Crohot',
        'category' => 'plage',
        'category_label' => 'Plage',
        'location' => 'Lège-Cap-Ferret',
        'tag' => 'Océan',
        'price_level' => 'Gratuit',
        'image' => 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=1200&auto=format&fit=crop',
        'description' => 'Océan, forêt de pins et coucher de soleil côté ouest. Une des plus belles plages sauvages du coin.',
        'instagram' => '#',
    ],
    // ACTIVITÉS
    [
        'id' => 'ile-aux-oiseaux',
        'name' => 'Île aux Oiseaux',
        'category' => 'activite',
        'category_label' => 'Activité',
        'location' => 'Bassin d\'Arcachon',
        'tag' => 'Pinasse',
        'price_level' => '€€',
        'image' => 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&auto=format&fit=crop',
        'description' => 'Balade en pinasse autour des célèbres cabanes tchanquées. Le symbole du bassin.',
        'instagram' => '#',
    ],
    [
        'id' => 'banc-arguin',
        'name' => 'Banc d\'Arguin',
        'category' => 'activite',
        'category_label' => 'Activité',
        'location' => 'Bassin d\'Arcachon',
        'tag' => 'Bateau',
        'price_level' => '€€',
        'image' => 'https://images.unsplash.com/photo-1468746840068-20a489ce0e15?w=1200&auto=format&fit=crop',
        'description' => 'Le banc de sable qui change de forme avec les marées. Pique-nique les pieds dans l\'eau turquoise.',
        'instagram' => '#',
    ],
    [
        'id' => 'surf-lacanau',
        'name' => 'Surf au Porge',
        'category' => 'activite',
        'category_label' => 'Activité',
        'location' => 'Le Porge',
        'tag' => 'Surf',
        'price_level' => '€€',
        'image' => 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=1200&auto=format&fit=crop',
        'description' => 'Session surf ou école pour débuter. Des vagues pour tous les niveaux, sans la foule de Lacanau.',
        'instagram' => '#',
    ],
    [
        'id' => 'parapente-pilat',
        'name' => 'Parapente à la Dune',
        'category' => 'activite',
        'category_label' => 'Activité',
        'location' => 'Dune du Pilat',
        'tag' => 'Sensations',
        'price_level' => '€€€',
        'image' => 'https://images.unsplash.com/photo-1601024445121-e5b82f020549?w=1200&auto=format&fit=crop',
        'description' => 'Décoller du haut de la Dune du Pilat, survoler la forêt et le bassin. L\'expérience ultime.',
        'instagram' => '#',
    ],
];

$community_groups = [
    [
        'name' => 'Bons plans Bassin',
        'description' => 'Le groupe pour repérer les meilleurs bons plans, restos et événements du week-end.',
        'members' => '420+',
        'emoji' => '🌅',
        'url' => '#',
    ],
    [
        'name' => 'Sorties Arcachon 18-30',
        'description' => 'Soirées, afterwork, rencontres. Pour les jeunes du bassin qui veulent bouger.',
        'members' => '180+',
        'emoji' => '🍹',
        'url' => '#',
    ],
    [
        'name' => 'Surf & océan',
        'description' => 'Sessions surf, covoiturage vers Le Porge et Lacanau, bulletins météo entre passionnés.',
        'members' => '95+',
        'emoji' => '🏄',
        'url' => '#',
    ],
    [
        'name' => 'Food du Bassin',
        'description' => 'On partage les nouvelles tables, cabanes à huîtres et adresses à tester.',
        'members' => '260+',
        'emoji' => '🦪',
        'url' => '#',
    ],
    [
        'name' => 'Familles du Bassin',
        'description' => 'Activités enfants, sorties familiales, bons plans week-end.',
        'members' => '310+',
        'emoji' => '👨‍👩‍👧',
        'url' => '#',
    ],
    [
        'name' => 'Concerts & festivals',
        'description' => 'Billetterie, covoiturage, alertes annulations : on ne rate plus une date.',
        'members' => '145+',
        'emoji' => '🎶',
        'url' => '#',
    ],
];

function get_weekend_events($events, $limit = 3) {
    $today = new DateTime();
    $highlighted = array_filter($events, fn($e) => !empty($e['highlight']));
    usort($highlighted, fn($a, $b) => strcmp($a['date'], $b['date']));
    return array_slice($highlighted, 0, $limit);
}

function get_spots_by_category($spots, $category) {
    return array_values(array_filter($spots, fn($s) => $s['category'] === $category));
}

function strftime_fr($month_num) {
    $months = [1=>'Jan',2=>'Fév',3=>'Mar',4=>'Avr',5=>'Mai',6=>'Juin',7=>'Juil',8=>'Août',9=>'Sep',10=>'Oct',11=>'Nov',12=>'Déc'];
    return $months[(int)$month_num] ?? '';
}
